title: 
  en: Page
  it: Pagina
  
options:
  move: false

image:
  icon: circle
  query: false

sections:
  slides:
    label: 
      en: Slides
      it: Slide
    type: pages
    layout: cards
    size: large
    template:
      - section-image
      - section-text
    info: '{{ page.intendedTemplate.title }}'
    search: true
    sortable: true
    empty: 
      en: >
        Add a new slide to the page
      it: >
        Aggiungi una nuova slide alla pagina
    image:
      cover: true
      ratio: 3/4
      back: white
      query: page.itemImage.toFile()